server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /api/v1
    session:
      cookie:
        same-site: none
        secure: true

spring:
  application:
    name: my-app
  profiles:
    active: "prod"

  flyway:
    enabled: false
  datasource:
    url: ${DB_HOST_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  session:
    store-type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


  cloud:
    aws:
      region:
        static: us-east-1

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}


app:
  jwt:
    issuer: "my-app"
    hmac-secret: ${APP_JWT_HS256_SECRET}
    access-token-ttl-seconds: 300
  ws:
    token-redis-prefix: "wsjti:"

  oauth2:
    login-success-url: ${LOGIN_SUCCESS_URL}
  sqs:
    queue-url: ${SQS_QUEUE_URL}

  domain-url: ${DOMAIN_URL}
  cors:
    extension-url: ${EXTENSION_URL}

---
# ===================================================================
# PRODUCTION PROFILE (prod)
# 1. Datasource:  PosgreSQL - AWS
# 2. Main_URL:    www.myfocustracker.com
# 3. SQS_URL:
# ===================================================================
spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      ssl:
        enabled: true
---
# ===================================================================
# Dev local PROFILE (dev).
# 1. DB:        Uses H2 in-memory database
# 2. MAIN_URL:  Localhost Domain
# ===================================================================
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      ssl:
        enabled: false
