server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /api/v1
    session:
      cookie:
        same-site: none
        secure: true


spring:
  application:
    name: my-app

  jpa:
    hibernate:
      ddl-auto: update # Use 'validate' for production to prevent accidental schema changes
    show-sql: true

  flyway:
    enabled: false

  profiles:
    active: "prod"

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}


app:
  jwt:
    issuer: "my-app"
    hmac-secret: ${APP_JWT_HS256_SECRET}
    access-token-ttl-seconds: 300


  ws:
    token-redis-prefix: "wsjti:"

  oauth2:
    login-success-url: ${LOGIN_SUCCESS_URL}
  sqs:
    queue-url: ${SQS_QUEUE_URL}

  domain-url: ${DOMAIN_URL}
  cors:
    extension-url: ${EXTENSION_URL}
---
# ===================================================================
# PRODUCTION PROFILE (prod)
# 1. Datasource:  PosgreSQL - AWS
# 2. Main_URL:    www.myfocustracker.com
# 3. SQS_URL:
# ===================================================================
spring:
  config:
    activate:
      on-profile: prod

  cloud:
    aws:
      region:
        static: us-east-1

  datasource:
    url: ${DB_HOST_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  session:
    store-type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
#      username: ${REDIS_USERNAME}
#      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
# ===================================================================
# Dev local PROFILE (dev).
# 1. DB:        Uses H2 in-memory database
# 2. MAIN_URL:  Localhost Domain
# ===================================================================
spring:
  config:
    activate:
      on-profile: dev

  cloud:
    aws:
      sqs:
        enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  session:
    store-type: jdbc

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop                       # Re-creates the schema on every test run

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 6379
      ssl:
        enabled: false