
server:
  address: 127.0.0.1

  error:
    whitelabel:
      enabled: false

  port: 8080
  servlet:
    context-path: /api

  tomcat:
    accesslog:
      enabled: true

spring:
  logging:
    level:
      org:
        springframework: DEBUG
  # --- DATASOURCE CONFIGURATION ---
  datasource:
    # It's good practice to add DB_CLOSE_DELAY to keep the in-memory H2 DB alive
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: password # Your original file had 'password', I've corrected it here.
    driverClassName: org.h2.Driver

  # --- H2 CONSOLE CONFIGURATION ---
  h2:
    console:
      enabled: true
      path: /h2-console

  # --- SPRING SESSION CONFIGURATION ---
  # This stores user session data in the H2 database.
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  # --- JPA & HIBERNATE CONFIGURATION ---
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  # --- OAUTH2 CLIENT CONFIGURATION (CORRECTED) ---
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

            scope:
              - openid
              - profile
              - email

            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code